#!/bin/bash

# This file must be copied to /etc/init.d/ and chmod to execute
# remember to change user and location then run:
# update-rc.d init_pumpkin defaults 99
sleep 90s
su ubuntu -c "nohup /home/ubuntu/workspace/pumpkin_ws/pumpkin.sh &"
