arduino: {port: /dev/ttyACM0}
left_arm:
  arduino: {port: /dev/ttyACM0}
  elbow:
    arduino: {pin: 9}
    ssc: {pin: 9, pulse_max: 1800, pulse_min: 1050, pulse_rest: 1500}
  shoulder_0:
    arduino: {pin: 6}
    ssc: {pin: 6, pulse_max: 2450, pulse_min: 650, pulse_rest: 2250}
  shoulder_1:
    arduino: {pin: 7}
    ssc: {pin: 7, pulse_max: 1950, pulse_min: 1025, pulse_rest: 1150}
  shoulder_2:
    arduino: {pin: 8}
    ssc: {pin: 8, pulse_max: 1850, pulse_min: 1175, pulse_rest: 1500}
  wrist_0:
    arduino: {pin: 10}
    ssc: {pin: 10, pulse_max: 2400, pulse_min: 650, pulse_rest: 1500}
  wrist_1:
    arduino: {pin: 11}
    ssc: {pin: 11, pulse_max: 0, pulse_min: 0, pulse_rest: 0}
right_arm:
  arduino: {port: /dev/ttyACM0}
  elbow:
    arduino: {pin: 3}
    ssc: {pin: 3, pulse_max: 1925, pulse_min: 1200, pulse_rest: 1500}
  shoulder_0:
    arduino: {pin: 0}
    ssc: {pin: 0, pulse_max: 2400, pulse_min: 675, pulse_rest: 800}
  shoulder_1:
    arduino: {pin: 1}
    ssc: {pin: 1, pulse_max: 2025, pulse_min: 1050, pulse_rest: 1925}
  shoulder_2:
    arduino: {pin: 2}
    ssc: {pin: 2, pulse_max: 1825, pulse_min: 1150, pulse_rest: 1500}
  wrist_0:
    arduino: {pin: 4}
    ssc: {pin: 4, pulse_max: 2400, pulse_min: 700, pulse_rest: 1500}
  wrist_1:
    arduino: {pin: 5}
    ssc: {pin: 5, pulse_max: 2125, pulse_min: 600, pulse_rest: 1500}
